apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsletterservice
spec:
  selector:
    matchLabels:
      app: newsletterservice
  template:
    metadata:
      labels:
        app: newsletterservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: newsletterservice
        ports:
        - containerPort: 9080
        env:
        - name: PORT
          value: "9080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:8080"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9080"]
---
apiVersion: v1
kind: Service
metadata:
  name: newsletterservice
spec:
  type: ClusterIP
  selector:
    app: newsletterservice
  ports:
  - name: grpc
    port: 9080
    targetPort: 9080